const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    NOT_FOUND_ERROR: 3,
    INTERNAL_SERVER_ERROR: 4,
    NOT_IMPLEMENTED_ERROR: 5,
    NOT_AUTHORIZED_ERROR: 6,
    NOT_ACCEPTABLE_ERROR: 7,
    BAD_REQUEST_ERROR: 8,
    CONFLICT_ERROR: 9,
    GONE_ERROR: 10,
    LENGTH_REQUIRED_ERROR: 11,
    PRECONDITION_FAILED_ERROR: 12,
}

export default EErrors;